import path from "node:path";
import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";
import { schema } from "@/db/schema";

// DATABASE_URL uses the libSQL/Turso "file:" URL convention (SPEC.md §15) so the
// same env var works in prod; better-sqlite3 wants a bare filesystem path.
const dbPath = (process.env.DATABASE_URL ?? "file:./local.db").replace(
  /^file:/,
  "",
);

// SQL files generated by `drizzle-kit generate` from src/db/schema/*.ts, plus
// hand-written custom migrations (e.g. the notes_fts virtual table, which
// isn't expressible in the Drizzle schema). Read from disk at runtime, so use
// an absolute path rather than one relative to this bundled module.
const migrationsFolder = path.join(process.cwd(), "src/db/migrations");

function createConnection() {
  const sqlite = new Database(dbPath);
  sqlite.pragma("journal_mode = WAL");
  sqlite.pragma("foreign_keys = ON");

  const db = drizzle({ client: sqlite, schema });

  try {
    migrate(db, { migrationsFolder });
  } catch (err) {
    throw new Error(
      `Failed to run database migrations (is FTS5 support missing from this SQLite build?): ${err}`,
    );
  }

  return db;
}

// Reuse the connection across Next.js dev-server Fast Refresh reloads instead
// of reopening the DB file (and re-running the DDL) on every edit.
declare global {
  var __inklyDb: ReturnType<typeof createConnection> | undefined;
}

export const db = globalThis.__inklyDb ?? createConnection();

if (process.env.NODE_ENV !== "production") {
  globalThis.__inklyDb = db;
}
